In [1]:
!pip install psycopg2
!pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: psycopg2 in /usr/local/lib/python3.9/dist-packages (2.9.5)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.9/dist-packages (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.9/dist-packages (from pandas) (2022.7.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.9/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.9/dist-packages (from pandas) (1.22.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [4]:
import psycopg2
import pandas as pd
# Connection parameters, yours will be different
param_dic = {
    "host"      : "tiny.db.elephantsql.com",
    "database"  : "hlxmmpdn",
    "user"      : "hlxmmpdn",
    "password"  : "RBeXAT4dZFTjaGnbngwFqhMnqtcyJI7a"
}
def connect(params_dic):
    """ Connect to the PostgreSQL database server """
    conn = None
    try:
        # connect to the PostgreSQL server
        print('Connecting to the PostgreSQL database...')
        conn = psycopg2.connect(**params_dic)
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        sys.exit(1) 
    print("Connection successful")
    return conn

def postgresql_to_dataframe(conn, select_query, column_names):
    """
    Tranform a SELECT query into a pandas dataframe
    """
    cursor = conn.cursor()
    try:
        cursor.execute(select_query)
    except (Exception, psycopg2.DatabaseError) as error:
        print("Error: %s" % error)
        cursor.close()
        return 1
    
    # Naturally we get a list of tupples
    tupples = cursor.fetchall()
    cursor.close()
    
    # We just need to turn it into a pandas dataframe
    df = pd.DataFrame(tupples, columns=column_names)
    return df

# Connect to the database
conn = connect(param_dic)

column_names = ['sepal_length','sepal_width','petal_length','petal_width','variety']

df_postEle = postgresql_to_dataframe(conn, "select sepal_width from iris_data", column_names)
df_postEle

Connecting to the PostgreSQL database...
Connection successful

ValueError: ignored

In [ ]:
!pip install mysqlclient
!pip install mysql-connector-python
!pip install pymysql

In [ ]:
import mysql.connector
import pandas as pd

koneksi=mysql.connector.connect(
    user = "root",
    password ="",
    host ="localhost",
    database ="prosain{200411100107}"
)
cur = koneksi.cursor()
cur.execute('SELECT * FROM petallength')
results = cur.fetchall()
koneksi.close()
df_mysql = pd.DataFrame(results, columns=['id','petallength'])
# df_mysql.drop(df_mysql.columns[[0]],axis=1,inplace=True)
df_mysql

In [ ]:
import psycopg2
import pandas as pd
import sys
# Connection parameters, yours will be different
param_dic = {
    "host"      : "localhost",
    "database"  : "prosaindata{2004111001007}",
    "user"      : "postgres",
    "password"  : "123456"
}
def connect(params_dic):
    """ Connect to the PostgreSQL database server """
    conn = None
    try:
        # connect to the PostgreSQL server
        print('Connecting to the PostgreSQL database...')
        conn = psycopg2.connect(**params_dic)
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        sys.exit(1) 
    print("Connection successful")
    return conn

def postgresql_to_dataframe(conn, select_query, column_names):
    """
    Tranform a SELECT query into a pandas dataframe
    """
    cursor = conn.cursor()
    try:
        cursor.execute(select_query)
    except (Exception, psycopg2.DatabaseError) as error:
        print("Error: %s" % error)
        cursor.close()
        return 1
    
    # Naturally we get a list of tupples
    tupples = cursor.fetchall()
    cursor.close()
    
    # We just need to turn it into a pandas dataframe
    df = pd.DataFrame(tupples, columns=column_names)
    return df

# Connect to the database
conn = connect(param_dic)

column_names = ['id','sepallength']

df_postLocal = postgresql_to_dataframe(conn, "select * from sepallength", column_names)
df_postLocal

In [ ]:
import pyodbc 
import pandas as pd
cnxn_str = ("Driver={odbc driver 17 for sql server};"
            "Server=DESKTOP-RV0GNHL\SERVER;"
            "Database=prosaindata{200411100107};"
            "Trusted_Connection=yes;")
cnxn = pyodbc.connect(cnxn_str)
cursor = cnxn.cursor()  
cursor.execute("SELECT * FROM petalwidth") 
row = cursor.fetchall() 
cursor.close()
data=[]
for i in row:
    data.append([i[0],i[1],i[2]])
df_sqlServer = pd.DataFrame(data, columns=['id','petalwidth','class'])
df_sqlServer

In [ ]:
# merge df
# result = pd.concat([df_postLocal, df_postEle,df_mysql, df_sqlServer], axis=1)
result = pd.merge(df_postLocal,df_sqlServer, how="inner", on=["id", "id"])
result

In [ ]:
result.drop(result.columns[[0,2,4,6]],axis=1,inplace=True)
result

In [ ]:
X = result.values[:, :4]
Y = result.values[:, 4]
print(X)